### PR TITLE
8u262 and 8u265 release note links

### PR DESCRIPTION
**Pull request by karianna**
##### Checklist

- [ ] `npm test` passes
- [ ] documentation is changed or added (if applicable)
- [ ] permission has been obtained to add new logo (if applicable)
- [ ] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by aahlenst — COMMENTED** [review]
I don't get security issues when opening the JBS links. For example, JDK-8238920 does not show up. 

https://foojay.io/java-8/?quarter=072020&tab=cve has them, however.

**Review by gdams — APPROVED** [review]

**Comment by aahlenst** [comment]
@gdams What about the security issues?

**Comment by gdams** [comment]
@aahlenst sorry I completely missed your comment, @karianna can you fix this?

**Comment by karianna** [comment]
Fixed in next PR

**Pull request merged**
