### PR TITLE
Fixing irrelevant css class name

### PR DESCRIPTION
**Pull request by brngylni**
##### Checklist

- [x] `npm test` passes
- [ ] documentation is changed or added (if applicable)
- [ ] permission has been obtained to add new logo (if applicable)
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by karianna** [comment]
@brngylni - I'm not sure what this issue is fixing?  The title is unclear.

**Comment by brngylni** [comment]
> @brngylni - I'm not sure what this issue is fixing?  The title is unclear.

This is just about fixing irrelevant class name.

**Comment by smlambert** [comment]
@karianna - I believe this fix relates to https://github.com/AdoptOpenJDK/openjdk-website/issues/645 (which was listed in the Good First Issues project that Outreachy candidates are taking issues from during their contribution period).

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
