### PR TITLE
Fix #284

### LINKED ISSUE #284: Archive page is only showing the latest release
See https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9
That page is only showing the latest release where it should also have the previous one on it as per https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/releases

### PR DESCRIPTION
**Pull request by johnoliver**
##### Checklist

- [x] `npm test` passes
- [x] documentation is changed or added
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by johnoliver** [comment]
The 10 hotspot release tag is a timestamp:
https://github.com/AdoptOpenJDK/openjdk10-releases/releases/tag/201807101745

**Comment by johnoliver** [comment]
You could edit then name of that release tag in github if you like

**Comment by karianna** [comment]
Hmm, whilst digging in:

how is https://staging.adoptopenjdk.net/285/archive.html?variant=openjdk9&jvmVariant=hotspot pulling that release when it doesn't seem to exist.

https://github.com/AdoptOpenJDK/openjdk9-releases/releases and https://github.com/AdoptOpenJDK/openjdk9-releases/tags are both empty

**Comment by johnoliver** [comment]
That is a bug on the release tag link, those releases are from the new repos:
https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/tag/jdk-9.0.4%2B11

**Comment by karianna** [comment]
OK, I've fixed the label - so I think this PR looks good.  I'll raise a separate issue to fix the release tag link

**Pull request merged**
