### PR TITLE
add jdk12 support to the website

### PR DESCRIPTION
**Pull request by gdams**
closes: https://github.com/AdoptOpenJDK/openjdk-website/issues/417

##### Checklist

- [x] `npm test` passes
- [x] documentation is changed or added
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by SueChaplain** [comment]
@gdams - I don't see 12 when I come to this page: https://staging.adoptopenjdk.net/418/ .. but I do see it on the latest release, nightlys, and archive page.

**Comment by gdams** [comment]
It's because it's not an LTS release. We only show LTS releases on the website. We could perhaps add the option to show `latest`. CC @karianna ?

**Comment by SueChaplain** [comment]
Looking good! It would be good to lose OpenJDK 9 & 10 from all but the archive page (think I'm correct in that these are no longer built) but I guess that is for another issue.

**Comment by karianna** [comment]
> Looking good! It would be good to lose OpenJDK 9 & 10 from all but the archive page (think I'm correct in that these are no longer built) but I guess that is for another issue.

I think it's OK to have the 9 and 10 builds for historical spelunkers.  But it's a good Q for the TSC, I'll dd a label so we pick it up.

**Comment by karianna** [comment]
> It's because it's not an LTS release. We only show LTS releases on the website. We could perhaps add the option to show `latest`. CC @karianna ?

TSC decision I think - adding label.

**Comment by gdams** [comment]
TSC has voted to not show JDK 12 on home page until first official Short term release has been shipped

**Comment by ben-walsh** [comment]
I understand the reasoning behind the decision for the home page. However, can we get the Nightly part of this completed ? It is always good to start getting feedback from the "early adopters" as soon as possible.

**Comment by karianna** [comment]
> I understand the reasoning behind the decision for the home page. However, can we get the Nightly part of this completed? It is always good to start getting feedback from the "early adopters" as soon as possible.

I'd be OK with that 0 this PR would need to change though.

**Comment by SueChaplain** [comment]
Hi @gdams or @karianna  -  I'm preparing some "What's new" content for the OpenJ9 0.13.0 release that will include a link to https://adoptopenjdk.net/releases.html?variant=openjdk12&jvmVariant=openj9. When do you expect this PR to merge please? I can put up "coming soon" and modify later to avoid a broken link, but would be good if I can avoid the extra step.

**Comment by karianna** [comment]
Assigned to @gdams - hopefully he can get some time to adjust this PR (but he's certainly loaded up today I know!)

**Comment by gdams** [comment]
@SueChaplain nightly builds are already available here https://adoptopenjdk.net/nightly.html?variant=openjdk12&jvmVariant=openj9. Once we have an official release we will merge this PR.

**Comment by SueChaplain** [comment]
@gdams - ok thanks .... will hang on for the main release page.

**Pull request merged**
