### PR TITLE
add further download redirections to home page

### PR DESCRIPTION
**Pull request by gdams**
This PR overrides the action of the main blue home button to redirect users to either Adoptium or Semuru

Preview Link is https://6154536f87b8dd136f39320b--vibrant-hugle-19d716.netlify.app/

##### Checklist

- [x] `npm test` passes
- [ ] documentation is changed or added (if applicable)
- [ ] permission has been obtained to add new logo (if applicable)
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

Screenshot 2021-09-29 at 12 23 03

Screenshot 2021-09-29 at 12 23 13

### CODE REVIEW

**Comment by tellison** [comment]
Can we loose/hide the "Download for <os>" and "Choose a version" elements?
We should also update the text above to be the "AdoptOpenJDK has moved" instruction, rather than putting it below the button. I can apply some thought to that.

**Comment by gdams** [comment]
> Can we loose/hide the "Download for " and "Choose a version" elements?

I can lose the download for element. If I delete the Choose a JVM element then we'll lose the ability to automatically direct users to Adoptium/Semuru?

**Comment by tellison** [comment]
Understood, that's why I didn't suggest losing the VM selector ;-)

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
