### PR TITLE
Fix typo on id for 8u272 identifier

### LINKED ISSUE #857: Release notes for 8u272 and 8u265 do not expand correctly
If you go to expand the [release notes for 8u265](https://adoptopenjdk.net/release_notes.html#jdk8u265), the notes for 8u272 are expanded.  The [notes for 8u272](https://adoptopenjdk.net/release_notes.html#jdk8u272) do not expand when clicking that [+/-] anchor icon.

### PR DESCRIPTION
**Pull request by tellison**
Fixes #857

### CODE REVIEW

**Comment by tellison** [comment]
Hmm, staging not working - maybe because it is a draft pull request?
Let me mark it ready for review (and then check the staging server ;-) )

**Comment by tellison** [comment]
For some reason I don't understand, this is not being staged correctly.

**Comment by ParkerM** [comment]
It seems to be working in staging from what I can tell: https://staging.adoptopenjdk.net/858/release_notes.html#jdk8u272

**Review by ParkerM — APPROVED** [review]

**Comment by karianna** [comment]
@ParkerM and @tellison - The staging-bot is currently disabled as it was picking up old PRs, I'll look to reenable now.

**Comment by karianna** [comment]
run tests

**Pull request merged**
