### PR TITLE
force users to navigate to adoptium.net or developer.ibm.com

### PR DESCRIPTION
**Pull request by gdams**
This change will force users to click the link on the download page which will direct them to the Temurin or IBM Semuru download pages. This is the next step in migrating users to the correct place.

PR can be landed when the TSC deems it to be appropriate 

##### Checklist

- [x] `npm test` passes
- [ ] documentation is changed or added (if applicable)
- [x] permission has been obtained to add new logo (if applicable)
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by tellison** [comment]
Feels like the right time to revive this, now there is a full release from Adoptium and Semeru. WDYT?

I might suggest we use a graphic indicator too to make it clear things have moved.

**Comment by gdams** [comment]
> I might suggest we use a graphic indicator too to make it clear things have moved.

@tellison it does with this PR! e.g:
Screenshot 2021-09-23 at 11 28 05


Screenshot 2021-09-23 at 11 27 51

**Comment by tellison** [comment]
I was thinking of a homepage replacement.
Is there a staging link for these changes?

**Review by karianna — APPROVED** [review]
LGTM

**Comment by gdams** [comment]
@tellison I think we should merge this as a starting point. I can continue to push users in the right way with more PR's

**Pull request merged**
