### PR TITLE
Add about page with license details and update README

### LINKED ISSUE #18: Add a tab / note about licensing (build scripts Apache v2, actual OpenJDK GPlv2 with Classpath)
Make licensing clear that the OpenJDK source code is GPLv2 and that the build scripts etc are Apache (You can you state what license you are in Github via a LICENSE file).

### PR DESCRIPTION
**Pull request by karianna**
Fixes #18

### CODE REVIEW

**Comment by karianna** [comment]
@Joe-Brady I couldn't quickly figure out how to nicely format a list inside a paragraph with the margin: auto style.

@tellison You'll probably want to review the wording carefully

**Comment by Joe-Brady** [comment]
screen shot 2017-03-23 at 21 28 05

**Comment by Joe-Brady** [comment]
I am about to submit a PR with a major change - I've added an HTML templating system with Handlebars.

Because it's such a big change, I've copied your changes from this PR into my source, and changed a few bits of CSS along the way (like the bit you asked for help on - screenshot above of the result).

What's the best approach, as my PR has these changes as well as the new HTML template system?

**Comment by karianna** [comment]
@Joe-Brady - Yeah that's totally fine, I'll definitely step aside for those with more expertise :-).  I'll close this as wontfix and figure out how to roll back locally

**Pull request closed without merging**
