### PR TITLE
IE support

### PR DESCRIPTION
**Pull request by allandequeiroz**
Hello guys, to support IE I used two techniques here.

- Transpile : Since we're using new language features like **const** transpiling was necessary to generate code that IE manage to work with.

- Polyfill : Here, instead of using a full library that includes lots of unnecessary things that we don't need slowing down the website, I used a more precise way to solve it, including just what we need, eg:
[findIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex)

So far we're ok with IE [10,11]. Do we need to support lower versions? Looks like that for older ones even look and feel breaks, if so this will ned a much bigger work with CSS.

closes: #111

### CODE REVIEW

**Comment by gdams** [comment]
staging: https://staging.adoptopenjdk.net

**Comment by allandequeiroz** [comment]
Cool!

**Comment by Joe-Brady** [comment]
Hi @allandequeiroz, huge thank you for the work!

I haven't checked on IE yet, but the changes seem to have broken the site on other browsers now (I've tested Chrome and Firefox on Mac so far...)

Something to do with `document.write` and Cloudflare... Any immediate thoughts on what this could be? I'm going to guess it's something to do with the changes to `function loadReleasesJSON(){}`, but really not sure!

screen shot 2017-06-18 at 12 35 58

**Comment by allandequeiroz** [comment]
Hey @Joe-Brady, no worries, I saw the same warnings here, then I've checked live and same thing. 

And since everything was apparently working fine, I decided just to ignore them.

**Comment by allandequeiroz** [comment]
What about range, IE [10,11] are enough? 

That was another assumption of mine. The target audience is composed of tech related people then maybe even that they are using IE let's say by company enforcement or some, they at least won't be using super old versions.

Do we have any analytics data about that?

**Comment by Joe-Brady** [comment]
@allandequeiroz I just had a look at our Analytics page... in the all-time data so far, there have been very few IE visitors, and all of them have been on IE 11.

I think you're right that the target audience are very unlikely to be using a browser older than IE 10!

**Pull request merged**
