### PR TITLE
change social logo

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] `npm test` passes
- [ ] documentation is changed or added
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Maldivia** [comment]
Is this really the logo you want to use? Assuming I'm seeing the right image from the above commit: 
https://raw.githubusercontent.com/AdoptOpenJDK/openjdk-website/54b8a71a5a979fecafc39e9665bc7279afca1d94/src/assets/social-logo.png

Then it has very visible compression artifacts, and overall looks like a poor job of scaling the picture.

Though, if this is actually visible on the cards on Twitter etc, I cannot say, as the staging site still references the existing/live image.

**Comment by gdams** [comment]
This logo isn’t actually used for anything. K was just updating it to be the full logo because the other one doesn’t make sense.

**Comment by karianna** [comment]
> This logo isn’t actually used for anything. K was just updating it to be the full logo because the other one doesn’t make sense.

Should we just remove this logo if it is not used for anything then?

**Comment by gdams** [comment]
> Should we just remove this logo if it is not used for anything then?

@karianna it's a required element in the organisation schema

**Comment by karianna** [comment]
> > Should we just remove this logo if it is not used for anything then?
> 
> @karianna it's a required element in the organization schema

Organization Schema? I'm not sure I follow.

**Comment by gdams** [comment]
It's used by google structured data: https://developers.google.com/search/docs/guides/intro-structured-data

**Pull request merged**
