### PR TITLE
add jck tick to landing pages

### PR DESCRIPTION
**Pull request by gdams**
This PR adds the JCK tick to the landing page

closes: https://github.com/AdoptOpenJDK/openjdk-website/issues/225

##### Checklist

- [x] `npm test` passes
- [ ] documentation is changed or added
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gdams** [comment]
requesting a review from @sxa555 as he has a linux system. Could you please confirm whether the `openjdk8_openj9` release now shows the tick on the landing page?

**Comment by sxa555** [comment]
Doesn't appear to :-(

image

**Comment by gdams** [comment]
@sxa555 fixing now

**Comment by sxa555** [comment]
Now working. Approving and merging

**Pull request merged**
