### PR TITLE
WIP: switch paddypower to be flutter group

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] `npm test` passes
- [ ] documentation is changed or added (if applicable)
- [x] permission has been obtained to add new logo (if applicable)
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by gdams** [comment]
hmm that logo isn't rendering on staging.

**Comment by karianna** [comment]
Needs to be ./dist

**Comment by karianna** [comment]
https://staging.adoptopenjdk.net/506/dist/assets/flutter.svg is there

**Comment by gdams** [comment]
yeah weirdly the other logos don't have that.

**Comment by karianna** [comment]
They're mostly external refs
Cheers,
Martijn

**Comment by gdams** [comment]
It's working fine on production so I'm not too worried aha

**Comment by ParkerM** [comment]
Note the leading slash and URI base path 😉 

image
image

**Pull request merged**
