### PR TITLE
Add Nightly range/date selectors, improve Nightly HTML generation logic

### PR DESCRIPTION
**Pull request by Joe-Brady**

### CODE REVIEW

**Comment by karianna** [comment]
```
Started by user Joe Brady
Building remotely on openjdk-staging-server (staging) in workspace /home/ubuntu/workspace/adoptopenjdk-website-staging
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
[adoptopenjdk-website-staging] $ bash -c "export > before.env"
[adoptopenjdk-website-staging] $ bash -c "source /root/.nvm/nvm.sh && NVM_NODEJS_ORG_MIRROR=null nvm install 6 && nvm use 6 && export > nvm.env"
bash: /root/.nvm/nvm.sh: Permission denied
ERROR: Failed to fork bash 
Finished: FAILURE
```

**Comment by Joe-Brady** [comment]
@karianna Was discussing this with George yesterday, this was what he has found:

It's an issue with nvm
The plugin got upgraded but I downgraded it just now
It's still broken though
It's using the root directory rather than /home so it doesn't have the right permissions

**Comment by karianna** [comment]
@Joe-Brady Can you run nvm in debug mode and get the output from that plugin and/or raise an issue with the plugin author?

**Comment by gdams** [comment]
staging server fixed, few linter errors though https://ci.adoptopenjdk.net/view/website/job/adoptopenjdk-website-staging/119/console

**Pull request merged**
