### PR TITLE
update support page

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

update support to match https://docs.google.com/document/d/19zO0yZidQEmDEVx8whnbsGDR2HpnQmP2mJ0nvDeQfsE/edit#

This is missing the links at the bottom as I am waiting for @tellison to let me know what links are needed.

### CODE REVIEW

**Comment by tellison** [comment]
Please remove the placeholder shown as {links} in 
`...support on these binaries {links}`

I think the text overall may benefit from a sprinkling of hyperlinks, but let's get this in place first and the links can be added later.

**Comment by gdams** [comment]
@tellison updated PTAL

**Comment by tellison** [comment]
One more tweak please.  Can we change the table column title from `End of Support` to `End of Availability`, since it is arguable that our project is not providing the direct support, and this title may be misleading.

**Comment by gdams** [comment]
@tellison updated PTAL

**Pull request merged**
