### PR TITLE
allow website to show ea builds

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] `npm test` passes
- [ ] documentation is changed or added (if applicable)
- [ ] permission has been obtained to add new logo (if applicable)
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

This PR adds an early access tag:

```js
  if ((version.pre) && (version.pre == 'ea')) {
    return true
  } else { 
    return false
  }
```
Sample:
Screenshot 2020-04-08 at 11 36 29

### CODE REVIEW

**Comment by lumpfish** [comment]
For the immediate requirement (AArch64 jdk11 openj9) must understanding is that the build pipeline will be submitted specifying 'release' (which I presume would make pre=ga).

**Comment by lumpfish** [comment]
Regarding the "pre" tag -  it is created when the "-ea" string is found in the java -version output, so a GA build will not carry the tag at all. So checking for pre=ea is all that is necessary in the web pages for tagging the builds (openjdk_version need not be checked and pre=ga is impossible)

**Comment by karianna** [comment]
@gdams It's hard to see evidence on staging that this worked - no binaries around to pick up?

**Comment by gdams** [comment]
@karianna that's correct, we will have to wait for the EA release to happen in order to see this

**Pull request merged**
