### PR TITLE
Add Installers to Home Page and Archive.

### LINKED ISSUE #170: Add Installers to home page and Archive
After the first installers (Win and Mac only at the moment) become available, they should automatically appear on the Latest page alongside the binaries, perhaps with a little tweaking required when that happens.

Once this looks 100%, the same functionality needs to be extended to the home page (perhaps just having the installer replace the binary on the big blue button when available), and to the Archive page.

### PR DESCRIPTION
**Pull request by EnriqueL8**
Fixes #170 
[ON STAGING](https://staging.adoptopenjdk.net) 

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

Added capability for installers to be displayed on the Archive page and set capability and preference for installer on the main home page button.

### CODE REVIEW

**Comment by karianna** [comment]
Can we see those hosted on staging?

**Comment by EnriqueL8** [comment]
@karianna  They are hosted on staging.

**Comment by karianna** [comment]
Got it, I assume installers isn't showing because we don't have any?

**Comment by EnriqueL8** [comment]
Yes, when we have the installers it will show a column with the current installers as such : ( ignore the .tar.gz extension it is just for testing)
image

**Comment by gdams** [comment]
Great first contribution here!

**Pull request merged**
