### PR TITLE
Use $releasever and $basearch in Centos example

### PR DESCRIPTION
**Pull request by makubi**
### Checklist
- [x] contribution guidelines followed [here](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by aahlenst** [comment]
I copied and pasted

```
cat <<EOF > /etc/yum.repos.d/adoptopenjdk.repo
[AdoptOpenJDK]
name=AdoptOpenJDK
baseurl=http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos/$releasever/$basearch
enabled=1
gpgcheck=1
gpgkey=https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
EOF
```

into a running CentOS 8 container and it resulted in

```
[AdoptOpenJDK]
name=AdoptOpenJDK
baseurl=http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos//
enabled=1
gpgcheck=1
gpgkey=https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
```

Any special prerequisites needed?

**Comment by aahlenst** [comment]
@karianna Does it work for you?

**Comment by makubi** [comment]
@aahlenst You are right, sorry. I did not test the copy & paste. What do you think about adding `\`s before the `$`? I will open another PR.

**Comment by aahlenst** [comment]
@makubi Could you elaborate what you're trying to achieve? Does for example CentOS define those variables in the environment so that they are automatically substituted with the correct values? Or should `$releasever` denote a placeholder that the user is expected to replace by hand? If the latter, why include `$` at all and it needs an explanation in the surrounding text.

**Comment by makubi** [comment]
@aahlenst Redhat defines those variables, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-using_yum_variables
I am trying to achieve a version-agnostic configuration. Other repositories like CentOS-Base use these variables as well.

**Comment by aahlenst** [comment]
Great. So please do whatever is needed to make the commands copy & paste compatible and I'll happily merge.

**Pull request merged**
