### PR TITLE
Updating the AdoptOpenJDK website to include the jvm variant.

### PR DESCRIPTION
**Pull request by adamfarley**
This makes the links consistent and improves the accuracy of error
messages.

See issue https://github.com/AdoptOpenJDK/openjdk-website/issues/276

Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>

### CODE REVIEW

**Comment by adamfarley** [comment]
Looks good on the staging server. Problem is resolved and the links are not consistent. If the jdk9 on openj9 nightly page says to check the latest releases page, it will link to the openj9 latest releases page rather than defaulting to the hotspot one.

@sxa555 - Can you review and merge when happy?

**Comment by sxa555** [comment]
Yep I'm happy with that after having a play on the staging server - thanks for the fix

**Comment by SueChaplain** [comment]
Hmm .. .the message doesn't work too well for the old OpenJ9 variant pages: https://adoptopenjdk.net/releases.html?variant=openjdk8-openj9

**Comment by johnoliver** [comment]
How did you get that link? It should be https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9 and when I look through pages for openjdk8+j9  I get actual results and don't see an error message.

**Comment by SueChaplain** [comment]
@johnoliver The OpenJ9 website was pointing to that link (https://www.eclipse.org/openj9/) .. we're just not up to date.  Don't worry, we're fixing now. Doesn't seem any point in trying to patch the message on the old page.

**Pull request merged**
