### PR TITLE
Add Sponsors page, change homepage link arrangement, change font to regular sans-serif (Fixes #67, Fixes #80)

### LINKED ISSUE #67: Port the infrastructure providers wiki to a supporters page
we should add a link on the website to https://github.com/AdoptOpenJDK/openjdk-build/wiki/Infrastructure-Providers so that we promote our donators/supporters

### LINKED ISSUE #80: QUESTION: Should the font weight be 'regular', instead of the current 'light'?
**EDIT: I've tried just using the default 'sans-serif' font instead of Open Sans. Think this might be the solution, as it's a halfway-house in terms of font weight. See what you think, I'll post more screenshots than this one if wanted:**

screen shot 2017-04-30 at 20 08 18

I originally used the lightest available font weight for the current font family "Open Sans". This was to achieve a modern and clean appearance.

However, I've noticed that it looks a bit TOO super-thin on some screens, especially mobile devices, and in some cases a bit hard to read.

I've attached screenshots of various pages of the website with a 'regular' font weight.

Thoughts?? @gdams @karianna @tellison 

screen shot 2017-04-30 at 19 12 29
screen shot 2017-04-30 at 19 13 22
screen shot 2017-04-30 at 19 12 42
screen shot 2017-04-30 at 19 12 49
screen shot 2017-04-30 at 19 12 58
screen shot 2017-04-30 at 19 13 05
screen shot 2017-04-30 at 19 13 11

### PR DESCRIPTION
**Pull request by Joe-Brady**
Fixes #67 (with future additions still to be made)
On [staging](http://staging.adoptopenjdk.net/sponsors.html)

Changed the layout of the links on the home page, so we now have a row of 'important'-looking links, and a second row for more useful links.

Used the LJC blurb as the only Tier-1. Can easily add IBM/jClarity/whoever we choose to add to Tier-1 once this has been decided.

Added a statement at the top as suggested, styled with a new class called 'callout'.

There are a few empty spaces where blurbs will be added, but raising this PR now as the consensus was to just go ahead without the blurbs.

A couple of CSS bits added to ensure the sponsors table is mobile responsive.

### CODE REVIEW

**Comment by gdams** [comment]
also please add it to the side bar

**Comment by Joe-Brady** [comment]
Good spot

**Comment by Joe-Brady** [comment]
Thanks!

**Comment by Joe-Brady** [comment]
Also added Google translate bar in footer. For some reason staging isn't picking up the new stylesheet changes - they're there in the PR, but not in the staging site after re-running the job?

**Comment by gdams** [comment]
I can see it on my mobile, I would suggest that we only enable the languages that we know we can support, let's start with Chinese as hopefully @gibfahn can take a look at the translation

**Comment by Joe-Brady** [comment]
@gdams Done - reduced to Chinese only for now. Very easy to change, you just update this bit in footer.handlebars:

`includedLanguages: 'en,zh-CN'`

**Comment by karianna** [comment]
@tellison Is it possible to get an IBM blurb relatively quickly?  Else we should merge this and open a new issue

**Comment by gdams** [comment]
@karianna the IBM blurb is going to take a while as it has to go through a lot of approvals first. @Joe-Brady do you want to remove the translation stuff for now and then we can land this, we'll create a new PR for the translations

**Comment by Joe-Brady** [comment]
@gdams I have removed the translation stuff - just commented out the block in footer.handlebars.

If we're not waiting for the Linaro blurb, then this is landable I'd say!

**Comment by LinuxSuRen** [comment]
I'd like to do some Chinese translation work, but no ideas how to start.

**Comment by karianna** [comment]
Hi @LinuxSuRen Thanks for showing your interest!  The best place to start is to sign up at adoptopenjdk.net/slack and join the #website channel - we'll get you started from there!

**Comment by LinuxSuRen** [comment]
@karianna Got it.

**Pull request merged**
